import figure_methods_spikes_spike_density
import figure_methods_coherence_slepian_sequences
import figure_methods_injected_currents_frequency

import figure_problems_noise_compare
import figure_problems_noise_correlation_histogram
import figure_problems_noise_to_region_correlation_vs_frequency
import figure_problems_shifting_window_noise_signal

import figure_results_coherence_heatmap_feedback
import figure_results_feedforward_conductance_frequency
import figure_results_lag_vs_correlation_lines
import figure_results_correlation_violinplots
import figure_results_correlation_heatmap

import figure_appendix_analysis_standard_heatmap_with_feedback


## Methods
figure_methods_injected_currents_frequency.save_default()
figure_methods_spikes_spike_density.save_default()
figure_methods_coherence_slepian_sequences.save_default()

## Problems
figure_problems_noise_compare.save_default()
figure_problems_noise_correlation_histogram.save_default()
figure_problems_noise_to_region_correlation_vs_frequency.save_default()
figure_problems_shifting_window_noise_signal.save_default()

## Results
figure_results_lag_vs_correlation_lines.save_default()
figure_results_coherence_heatmap_feedback.save_default()
figure_results_feedforward_conductance_frequency.save_default()
figure_results_correlation_violinplots.save_default()
figure_results_correlation_heatmap.save_default()

## Appendix
figure_appendix_analysis_standard_heatmap_with_feedback.save_default()
